version: '3'
name: LAP2-Challenge
services:
  server:
    image: node:12.18.4
    working_dir: /code
    ports: 
      - 3000:3000
    environment: 
      - PGUSER=futureproof
      - PGHOST=db
      - PGPASSWORD=shelterpass
      - PGDATABASE=shelter
      - PGPORT=5432
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./api
        target: /code
    command: bash -c "npm install && npm start"

  db:
    image: postgres:latest
    container_name: lap2database
    volumes:
      - "dbdata:/var/lib/postgresql/data"
      - "./db:/docker-entrypoint-initdb.d/:ro"
    environment: 
      - POSTGRES_DB=shelter
      - POSTGRES_USER=futureproof
      - POSTGRES_PASSWORD=shelterpass
volumes:
  dbdata: